# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gscraper}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Postmodern"]
  s.date = %q{2010-08-24}
  s.description = %q{GScraper is a web-scraping interface to various Google Services.}
  s.email = %q{postmodern.mod3@gmail.com}
  s.extra_rdoc_files = [
    "ChangeLog.md",
    "README.md"
  ]
  s.files = [
    ".gitignore",
    ".specopts",
    ".yardopts",
    "COPYING.txt",
    "ChangeLog.md",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "gscraper.gemspec",
    "lib/gscraper.rb",
    "lib/gscraper/extensions.rb",
    "lib/gscraper/extensions/uri.rb",
    "lib/gscraper/extensions/uri/http.rb",
    "lib/gscraper/extensions/uri/query_params.rb",
    "lib/gscraper/gscraper.rb",
    "lib/gscraper/has_pages.rb",
    "lib/gscraper/hosts.rb",
    "lib/gscraper/languages.rb",
    "lib/gscraper/licenses.rb",
    "lib/gscraper/page.rb",
    "lib/gscraper/search.rb",
    "lib/gscraper/search/ajax_query.rb",
    "lib/gscraper/search/exceptions.rb",
    "lib/gscraper/search/exceptions/blocked.rb",
    "lib/gscraper/search/page.rb",
    "lib/gscraper/search/query.rb",
    "lib/gscraper/search/result.rb",
    "lib/gscraper/search/search.rb",
    "lib/gscraper/search/web_query.rb",
    "lib/gscraper/sponsored_ad.rb",
    "lib/gscraper/sponsored_links.rb",
    "lib/gscraper/version.rb",
    "spec/extensions/uri/http_spec.rb",
    "spec/extensions/uri/query_params_spec.rb",
    "spec/gscraper_spec.rb",
    "spec/has_pages_examples.rb",
    "spec/has_sponsored_links_examples.rb",
    "spec/helpers/query.rb",
    "spec/helpers/uri.rb",
    "spec/languages_spec.rb",
    "spec/page_has_results_examples.rb",
    "spec/search/ajax_query_spec.rb",
    "spec/search/page_has_results_examples.rb",
    "spec/search/query_spec.rb",
    "spec/search/web_query_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.has_rdoc = %q{yard}
  s.homepage = %q{http://github.com/postmodern/gscraper}
  s.licenses = ["GPL-2"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{GScraper is a web-scraping interface to various Google Services.}
  s.test_files = [
    "spec/extensions/uri/http_spec.rb",
    "spec/extensions/uri/query_params_spec.rb",
    "spec/gscraper_spec.rb",
    "spec/has_pages_examples.rb",
    "spec/has_sponsored_links_examples.rb",
    "spec/helpers/query.rb",
    "spec/helpers/uri.rb",
    "spec/languages_spec.rb",
    "spec/page_has_results_examples.rb",
    "spec/search/ajax_query_spec.rb",
    "spec/search/page_has_results_examples.rb",
    "spec/search/query_spec.rb",
    "spec/search/web_query_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json_pure>, ["~> 1.4.0"])
      s.add_runtime_dependency(%q<mechanize>, ["~> 1.0.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.0"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3.0"])
    else
      s.add_dependency(%q<json_pure>, ["~> 1.4.0"])
      s.add_dependency(%q<mechanize>, ["~> 1.0.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.0"])
      s.add_dependency(%q<rspec>, ["~> 1.3.0"])
    end
  else
    s.add_dependency(%q<json_pure>, ["~> 1.4.0"])
    s.add_dependency(%q<mechanize>, ["~> 1.0.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<rake>, ["~> 0.8.7"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.0"])
    s.add_dependency(%q<rspec>, ["~> 1.3.0"])
  end
end

